### ISSUE TITLE
Error: Can't locate model data

### ISSUE THREAD

**Issue by DaveFerger** [oroszgy/spacy-hungarian-models#1]
``` python -m spacy link hu_tagger_web_md hu ```

Get error:
```
    Can't locate model data
    The data should be located in hu_tagger_web_md
```

and in rasa_nlu.train
```
…
IOError: Can't find model 'hu'
```

**Comment by oroszgy** [comment]
Hey, sorry for the late reply. Can you provide more details? (Spacy version, Python version, OS)
