### ISSUE TITLE
BadZipFile error

### ISSUE THREAD

**Issue by begdaniel** [oroszgy/spacy-hungarian-models#4]
I get an error when trying to install through pip.

zipfile.BadZipFile: Bad CRC-32 for file 'hu_core_ud_lg/hu_core_ud_lg-0.2.0/tagger/model'

any ideas?

**Comment by tpetkovich** [comment]
> 
> 
> I get an error when trying to install through pip.
> 
> zipfile.BadZipFile: Bad CRC-32 for file 'hu_core_ud_lg/hu_core_ud_lg-0.2.0/tagger/model'
> 
> any ideas?

I had the same problem with the hu_core_ud_lg-0.2.0-py3-none-any.whl file. It must be a corrupted file.
But the tarball version works for me: https://github.com/oroszgy/spacy-hungarian-models/releases/download/hu_core_ud_lg-0.2.0/hu_core_ud_lg-0.2.0.tar.gz

**Comment by begdaniel** [comment]
> > I get an error when trying to install through pip.
> > zipfile.BadZipFile: Bad CRC-32 for file 'hu_core_ud_lg/hu_core_ud_lg-0.2.0/tagger/model'
> > any ideas?
> 
> I had the same problem with the hu_core_ud_lg-0.2.0-py3-none-any.whl file. It must be a corrupted file.
> But the tarball version works for me: https://github.com/oroszgy/spacy-hungarian-models/releases/download/hu_core_ud_lg-0.2.0/hu_core_ud_lg-0.2.0.tar.gz

This worked like a charm! Thanks a lot!
