### ISSUE TITLE
Error during download UD_Hungarian-Szeged

### ISSUE THREAD

**Issue by laklaja** [oroszgy/spacy-hungarian-models#6]
Error during make install. Have the permissions of this dependency changed?

`mkdir -p ./data/raw/UD_Hungarian-Szeged
git clone git@github.com:UniversalDependencies/UD_Hungarian-Szeged.git ./data/raw/UD_Hungarian-Szeged

Cloning into './data/raw/UD_Hungarian-Szeged'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
make: *** [data/raw/UD_Hungarian-Szeged] Error 128`

**Comment by oroszgy** [comment]
Hey,

it looks like an ssh error on your side. Anyway, changing the clone url to `https://github.com/UniversalDependencies/UD_Hungarian-Szeged.git` should help you out.

Hope it helps.

**Comment by laklaja** [comment]
Sorry, but I have tried the following installation in several environments, but I gave the same output:

`
$ git clone https://github.com/oroszgy/spacy-hungarian-models.git
Cloning into 'spacy-hungarian-models'...
remote: Enumerating objects: 214, done.
remote: Total 214 (delta 0), reused 0 (delta 0), pack-reused 214
Receiving objects: 100% (214/214), 154.96 KiB | 0 bytes/s, done.
Resolving deltas: 100% (100/100), done.
Checking connectivity... done.

$ cd ./spacy-hungarian-models/

$ make install
make: *** No rule to make target 'install'.  Stop.
laklaja@gupi:~/spacy-hungarian-models$ make all
mkdir -p ./data/raw/UD_Hungarian-Szeged
git clone git@github.com:UniversalDependencies/UD_Hungarian-Szeged.git ./data/raw/UD_Hungarian-Szeged
Cloning into './data/raw/UD_Hungarian-Szeged'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Makefile:60: recipe for target 'data/raw/UD_Hungarian-Szeged' failed
make: *** [data/raw/UD_Hungarian-Szeged] Error 128
`
or 
`git clone git@github.com:UniversalDependencies/UD_Hungarian-Szeged.git ./data/raw/UD_Hungarian-Szeged
Cloning into './data/raw/UD_Hungarian-Szeged'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
make: *** [data/raw/UD_Hungarian-Szeged] Error 128
`
This github url of the UD corpora is part of your Makefile. Can you check it please.
