### ISSUE TITLE
what was the dataset used to train this models ?

### ISSUE THREAD

**Issue by thak123** [oroszgy/spacy-hungarian-models#7]
Dataset used to train and test this model Can anyone point me to that ?

**Comment by oroszgy** [comment]
Sure, you can find them linked in the release descriptions: https://github.com/oroszgy/spacy-hungarian-models/releases/tag/hu_core_ud_lg-0.3.1

Also, have a look at the [Makefile](https://github.com/oroszgy/spacy-hungarian-models/blob/master/Makefile) which points to exact data sources.
